### ISSUE TITLE
Löschen und synchronisieren

### ISSUE THREAD

**Issue by hurzl** [hampelratte/lazybones#11]
Will ich z.B. eine laufende Aufnahme löschen, kommt oft die Meldung, dass man erst synchronisieren soll, könnte das nicht automatisch geschehen?

**Comment by hampelratte** [comment]
Leider nicht. Das Problem hier ist, dass VDR leider keine IDs für seine Aufnahmen benutzt, sondern sie einfach durchnummeriert. Wenn eine Aufnahme gelöscht wird, oder eine neue hinzukommt, wird einfach alles wieder durchnummeriert. Dadurch kann es im schlimmsten Fall passieren (wenn du Aufnahme 1 löschst), dass nach dem Löschen alle Aufnahmen eine neue ID haben. Deshalb verlangt der VDR, dass man vor dem Löschen synchronisiert.

Das automatische Synchronisieren vor dem Löschen würde deshalb nicht funktionieren, weil die Aufnahme auf Seite des VDR vielleicht schon eine andere Nummer bekommen hat. 
Beispiel: Du wählst zum Beispiel Aufnahme 12 (sagen wir mal Tatort) zum Löschen aus. Der VDR hat zwischenzeitlich aber neu nummeriert. Tatort ist jetzt 11 und Tagesschau hat 12.
Der Ablauf wäre also:
* Tatort (12) löschen (Aufnahme 12 ist aber bei VDR schon längst Tagesschau)
* Lazy Bones synchronisiert 
* Lazy Bones löscht Aufnahme 12
* Tagesschau ist weg
* Tatort immer noch da

Mich hat das bei der ersten Implementierung schon genervt. Weil man deshalb auch immer alles neu laden muss. Aber es ist halt so. Man könnte höchstens mal an Klaus appellieren, dass er das ändert und die Nummern gegen IDs austauscht.

**Comment by hurzl** [comment]
Ja, aber er weiß doch, dass sychronisiert werden muss, also das ginge schon mal automatisch. Und bei laufenden Aufnahmen fragt er sowieso nach, Und dafür könnte er Titel vergleichen und die Zeiten? Die hat man doch vorher und nachher?

**Comment by hampelratte** [comment]
Lazy Bones weiß nicht unbedingt, dass synchronisiert werden muss. Man könnte das vor jedem Löschen automatisch machen, aber dann müsste man tatsächlich vergleichen, wie Du vorschlägst. So etwas ähnliches mache ich schon beim Anlegen von Timern, um sicherzustellen, dass wirklich die passende Sendung aufgenommen wird (manchmal unterscheiden sich die EPGs ja). Das macht die Dinge aber sehr viel komplizierter. Wie gesagt, diese ganze "Nummern statt IDs Geschichte" ist broken by design. Und der Aufwand, das Problem durch Workarounds auszugleichen, ist mir im Moment zu hoch.
